services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: unless-stopped
