events {}

http {
    include mime.types;
    server_tokens off;

    server {
        listen 3000;
        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://app:8080;
        }

        location /l/ {
            proxy_pass http://app:8080/api/links/redirect/;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
